# Simple Help Tickets
# &0 = Black  |  &1 = DarkGray
# &2 = GRAY   |  &w = White
# &r = Red    |  &R = DarkRed
# &y = YELLOW |  &Y = Gold
# &g = Green  |  &G = DarkGreen
# &c = Cyan   |  &C = DarkCyan
# &b = Blue   |  &B = DarkBlue
# &p = Purple |  &P = DarkPurple
#
#
# Permisions:
# sht.ticket - Create help tickets
# sht.admin - Administrate tickets
#
# Commands:
# Change the commands to fit your needs, just define them after Commands.
# Example:
# realcommand: yourcommand
MaxTickets: 3
TicketExpiration: 7
NotifyAdminOnTicketClose: true
MultiWorld: false
OnJoin:
  DisplayTicketAdmin: true
  DisplayTicketUser: true
MySQL:
  USE_MYSQL: false
  hostname: localhost
  hostport: 3306
  database: tickets
  user: MYSQLUSER
  password: MYSQLPASS