name: SimpleHelpTickets
main: me.odium.simplehelptickets.SimpleHelpTickets
version: 1.7
commands:
   sht:
      aliases: [helptickets, simplehelptickets, support]
      description: Help Menu
      permission:
      usage: /sht
   ticket:
      aliases: [helpme, grief]
      description: Open a help ticket
      permission: sht.ticket
      usage: /ticket <Description>
   tickets:
      description: Review your/all help tickets
      permission:
      usage: /tickets [ac]  
   closeticket:
      aliases: [tstäng]
      description: close or reopen a help ticket
      permission:
      usage: /closeticket [r] <#>
   replyticket:
      aliases: [tsvara]
      description: reply to a help ticket
      permission: sht.ticket
      usage: /replyticket <#> <reply>
   taketicket:
      aliases: [tansvar]
      description: Assign self to a help ticket
      permission: sht.admin
      usage: /taketicket <#>
   checkticket:
      aliases: [chticket, tkolla, tinfo]
      description: check your/a help ticket
      permission:
      usage: /checkticket <#>
   delticket:
      aliases: [dticket, tabort]
      description: Delete a ticket
      permission:
      usage: /delticket <#>
   purgetickets:
      aliases: [ptickets, rensatickets]
      description: Purge all expired tickets
      permission: sht.purge
      usage: /purgetickets
   klart:
      description: Används för att få sitt hus inspekterat
      permission: sht.klart
      usage: /klart